# Generated by Django 4.2 on 2024-07-11 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='año',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=4),
        ),
        migrations.AlterField(
            model_name='movies',
            name='type',
            field=models.CharField(choices=[('Miedo', 'Miedo'), ('Accion', 'Accion'), ('Romance', 'Romance'), ('Comedia', 'Comedia'), ('Terror', 'Terror')], max_length=30),
        ),
        migrations.AlterField(
            model_name='movies',
            name='director',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=4),
        ),
        migrations.AlterField(
            model_name='movies',
            name='sinopsis',
            field=models.TextField(default=10),
        )
    ]
