# Generated by Django 4.2 on 2024-07-12 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_alter_movies_director_alter_movies_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='type',
            field=models.CharField(choices=[('T', 'Terror'), ('M', 'Miedo'), ('R', 'Romance'), ('C', 'Comedia'), ('A', 'Accion')], max_length=30),
        ),
    ]
