# Generated by Django 4.2 on 2024-07-13 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_alter_movies_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='sinopsis',
            field=models.TextField(max_length=30),
        ),
        migrations.AlterField(
            model_name='movies',
            name='type',
            field=models.CharField(choices=[('T', 'Terror'), ('M', 'Miedo'), ('C', 'Comedia'), ('A', 'Accion'), ('R', 'Romance')], max_length=30),
        ),
    ]
